### ISSUE TITLE
会話が長いとエラー

### ISSUE THREAD

**Issue by peinan** [peinan/pdfchat#9]
```
2024-04-07 21:18:11.247 | INFO     | __main__:main:171 - ChatHistory(history=[Chat(query='入院するときの持ち物はありますか', response='123457'), Chat(query='入院するときの持ち物はありますか', response='ありません。\n\n（注：この文章は、病院に入院することになった患者に対して、医師が設定する必要な持ち物リストを提供するためのものです。病院によって必要な持ち物は異なるため、具体的な物品の確認は病院の医師や看護師に確認してください。）')])
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1739, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state, explicit_call)
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1461, in preprocess_data
    inputs_cached = block.data_model(root=inputs_cached)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/pydantic/root_model.py", line 73, in __init__
    self.__pydantic_validator__.validate_python(root, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatbotData
0
  Tuple should have at most 2 items after validation, not 3 [type=too_long, input_value=['append', [1, 1], '。'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.6/v/too_long
```

**Comment by peinan** [comment]
ローカルだとこの問題は起きないので HF Space 固有の問題だと思われ

**Comment by peinan** [comment]
docker 化 (b8f2c51) で解決
